import { Platform, StatusBar, StyleSheet } from "react-native";

const topInset = Platform.OS === "android" ? StatusBar.currentHeight || 0 : 0;
const bottomInset = Platform.OS === "android" ? 18 : 10;
const palette = {
  emerald900: "#063f35",
  emerald800: "#075246",
  emerald700: "#0b6b5a",
  emerald600: "#10826d",
  mintWash: "#eef8f3",
  mintSoft: "#f6fcf8",
  ivory: "#fffaf0",
  ivoryDeep: "#fff3d7",
  gold: "#d8a43b",
  goldSoft: "#f8e7b8",
  coral: "#e9674d",
  coralDark: "#b94132",
  coralSoft: "#fff0e8",
  ink: "#17212b",
  slate: "#647383",
  border: "#e8dcc7",
  borderStrong: "#d8bf85",
  white: "#ffffff",
};

export const styles = StyleSheet.create({
  app: {
    flex: 1,
    backgroundColor: palette.emerald900,
  },
  loadingScreen: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: palette.mintWash,
  },
  authScreen: {
    flex: 1,
    justifyContent: "center",
    paddingHorizontal: 20,
    paddingTop: 24 + topInset,
    paddingBottom: 24 + bottomInset,
    backgroundColor: palette.mintWash,
  },
  authPanel: {
    gap: 14,
    width: "100%",
    maxWidth: 430,
    alignSelf: "center",
  },
  brandMark: {
    width: 70,
    height: 70,
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
    borderWidth: 2,
    borderColor: palette.gold,
    borderRadius: 22,
    backgroundColor: palette.emerald900,
    shadowColor: palette.emerald900,
    shadowOpacity: 0.22,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 8 },
    elevation: 5,
  },
  brandImage: {
    width: 70,
    height: 70,
  },
  brandText: {
    color: palette.white,
    fontSize: 20,
    fontWeight: "900",
  },
  authTitle: {
    color: palette.ink,
    fontSize: 32,
    fontWeight: "900",
  },
  authTitleRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 12,
  },
  authTitleText: {
    flex: 1,
    gap: 6,
  },
  authCopy: {
    color: palette.slate,
    fontSize: 16,
    lineHeight: 24,
  },
  phoneShell: {
    flex: 1,
    alignSelf: "center",
    width: "100%",
    maxWidth: 430,
    backgroundColor: palette.mintWash,
  },
  header: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 12,
    paddingHorizontal: 16,
    paddingTop: 18 + topInset,
    paddingBottom: 14,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(216, 164, 59, 0.35)",
    backgroundColor: palette.emerald900,
  },
  headerText: {
    flex: 1,
    minWidth: 0,
  },
  userEmail: {
    marginBottom: 4,
    color: palette.goldSoft,
    fontSize: 13,
  },
  title: {
    color: palette.white,
    fontSize: 27,
    fontWeight: "900",
  },
  headerActions: {
    alignItems: "flex-end",
    gap: 8,
  },
  languageSwitch: {
    flexDirection: "row",
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "rgba(248, 231, 184, 0.45)",
    borderRadius: 10,
    backgroundColor: "rgba(255, 250, 240, 0.12)",
  },
  languageButton: {
    minWidth: 34,
    height: 34,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 6,
  },
  languageButtonActive: {
    backgroundColor: palette.gold,
  },
  languageText: {
    color: palette.goldSoft,
    fontSize: 12,
    fontWeight: "900",
  },
  languageTextActive: {
    color: palette.emerald900,
  },
  logoutButton: {
    minWidth: 54,
    minHeight: 40,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 10,
    borderWidth: 1,
    borderColor: "rgba(248, 231, 184, 0.55)",
    borderRadius: 10,
    backgroundColor: palette.ivory,
  },
  logoutText: {
    color: palette.emerald800,
    fontSize: 14,
    fontWeight: "900",
  },
  content: {
    gap: 14,
    paddingHorizontal: 16,
    paddingBottom: 96 + bottomInset,
  },
  card: {
    gap: 14,
    padding: 16,
    borderWidth: 1,
    borderColor: palette.border,
    borderRadius: 8,
    backgroundColor: palette.white,
    shadowColor: palette.emerald900,
    shadowOpacity: 0.07,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
    elevation: 2,
  },
  statsCard: {
    flexDirection: "row",
    justifyContent: "space-between",
  },
  inlineStats: {
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 10,
  },
  stat: {
    flex: 1,
    gap: 5,
    minWidth: 0,
  },
  statLabel: {
    color: palette.slate,
    fontSize: 12,
    minHeight: 30,
  },
  statValue: {
    color: palette.emerald900,
    fontSize: 19,
    fontWeight: "900",
  },
  sectionTitle: {
    color: palette.ink,
    fontSize: 20,
    fontWeight: "900",
  },
  helperText: {
    color: palette.slate,
    fontSize: 16,
    lineHeight: 24,
  },
  field: {
    gap: 8,
  },
  label: {
    color: palette.emerald700,
    fontSize: 13,
    fontWeight: "700",
  },
  input: {
    minHeight: 52,
    paddingHorizontal: 14,
    borderWidth: 1,
    borderColor: palette.border,
    borderRadius: 10,
    backgroundColor: palette.ivory,
    color: palette.ink,
    fontSize: 16,
  },
  primaryButton: {
    minHeight: 58,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 8,
    backgroundColor: palette.coral,
    shadowColor: palette.coral,
    shadowOpacity: 0.24,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
    elevation: 3,
  },
  primaryPressed: {
    backgroundColor: palette.coralDark,
  },
  primaryText: {
    color: palette.white,
    fontSize: 17,
    fontWeight: "900",
    textAlign: "center",
  },
  disabled: {
    opacity: 0.65,
  },
  linkButton: {
    alignSelf: "center",
    paddingVertical: 8,
  },
  linkText: {
    color: palette.emerald700,
    fontSize: 15,
    fontWeight: "800",
  },
  errorText: {
    color: palette.coralDark,
  },
  statusText: {
    color: palette.slate,
    fontSize: 15,
  },
  scanGrid: {
    gap: 10,
  },
  actionTile: {
    gap: 4,
    padding: 14,
    borderWidth: 1,
    borderColor: palette.border,
    borderRadius: 8,
    backgroundColor: palette.ivory,
  },
  pressed: {
    opacity: 0.75,
  },
  actionTitle: {
    color: palette.emerald900,
    fontSize: 17,
    fontWeight: "900",
  },
  actionCopy: {
    color: palette.slate,
    fontSize: 14,
  },
  selectedFile: {
    gap: 4,
    padding: 14,
    borderWidth: 1,
    borderColor: palette.border,
    borderRadius: 8,
    backgroundColor: palette.ivory,
  },
  selectedLabel: {
    color: palette.slate,
    fontSize: 12,
  },
  selectedName: {
    color: palette.ink,
    fontSize: 16,
    fontWeight: "800",
  },
  segmented: {
    flexDirection: "row",
    minHeight: 44,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: palette.border,
    borderRadius: 8,
    backgroundColor: palette.ivory,
  },
  segmentButton: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 10,
  },
  segmentButtonActive: {
    backgroundColor: palette.emerald700,
  },
  segmentText: {
    color: palette.slate,
    fontSize: 14,
    fontWeight: "900",
  },
  segmentTextActive: {
    color: palette.white,
  },
  manualForm: {
    gap: 14,
  },
  chipGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  categoryChip: {
    minHeight: 38,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 12,
    borderWidth: 1,
    borderColor: palette.border,
    borderRadius: 999,
    backgroundColor: palette.ivory,
  },
  categoryChipActive: {
    borderColor: palette.coral,
    backgroundColor: palette.coralSoft,
  },
  categoryChipText: {
    color: palette.slate,
    fontSize: 13,
    fontWeight: "900",
  },
  categoryChipTextActive: {
    color: palette.coralDark,
  },
  manualItem: {
    gap: 10,
    padding: 12,
    borderWidth: 1,
    borderColor: palette.border,
    borderRadius: 8,
    backgroundColor: palette.ivory,
  },
  manualItemHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  twoColumn: {
    flexDirection: "row",
    gap: 10,
  },
  flexInput: {
    flex: 1,
    minWidth: 0,
  },
  secondaryButton: {
    minHeight: 48,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: palette.emerald700,
    borderRadius: 10,
    backgroundColor: palette.white,
  },
  secondaryText: {
    color: palette.emerald700,
    fontSize: 15,
    fontWeight: "900",
  },
  smallButton: {
    minHeight: 34,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 10,
    borderRadius: 8,
    backgroundColor: palette.goldSoft,
  },
  smallButtonText: {
    color: palette.emerald800,
    fontSize: 12,
    fontWeight: "900",
  },
  actionRow: {
    gap: 6,
  },
  proCard: {
    borderColor: palette.border,
    backgroundColor: palette.white,
  },
  proCardActive: {
    borderColor: palette.gold,
    backgroundColor: palette.ivory,
  },
  proHeader: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 10,
  },
  proBadge: {
    maxWidth: 118,
    paddingHorizontal: 8,
    paddingVertical: 7,
    overflow: "hidden",
    borderRadius: 8,
    backgroundColor: palette.goldSoft,
    color: palette.emerald900,
    fontSize: 12,
    fontWeight: "900",
    textAlign: "center",
  },
  invoiceCard: {
    borderTopWidth: 1,
    borderTopColor: palette.border,
  },
  invoiceSummary: {
    minHeight: 70,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    paddingVertical: 12,
  },
  invoiceText: {
    flex: 1,
    gap: 4,
  },
  invoiceTitle: {
    color: palette.ink,
    fontSize: 18,
    fontWeight: "900",
  },
  invoiceMeta: {
    color: palette.slate,
    fontSize: 13,
  },
  invoiceAmount: {
    color: palette.emerald800,
    fontSize: 17,
    fontWeight: "900",
    maxWidth: 120,
    textAlign: "right",
  },
  itemList: {
    gap: 10,
    paddingBottom: 14,
    paddingLeft: 12,
  },
  retryPanel: {
    gap: 10,
    paddingBottom: 14,
  },
  itemRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    paddingTop: 10,
    borderTopWidth: 1,
    borderTopColor: palette.border,
  },
  itemName: {
    color: palette.ink,
    fontSize: 15,
    fontWeight: "800",
  },
  itemPrice: {
    color: palette.emerald800,
    fontSize: 15,
    fontWeight: "900",
  },
  categoryRow: {
    gap: 10,
    paddingVertical: 14,
    borderTopWidth: 1,
    borderTopColor: palette.border,
  },
  categoryRowSelected: {
    paddingHorizontal: 10,
    borderRadius: 10,
    backgroundColor: palette.ivory,
  },
  categoryMeta: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  categoryDot: {
    width: 12,
    height: 12,
    borderRadius: 6,
  },
  categoryName: {
    flex: 1,
    minWidth: 0,
    color: palette.ink,
    fontSize: 17,
    fontWeight: "900",
  },
  categoryCount: {
    color: palette.slate,
    fontSize: 13,
  },
  categoryAmount: {
    color: palette.emerald800,
    fontSize: 16,
    fontWeight: "900",
    maxWidth: 110,
    textAlign: "right",
  },
  categoryBar: {
    height: 8,
    overflow: "hidden",
    borderRadius: 999,
    backgroundColor: palette.goldSoft,
  },
  categoryFill: {
    height: "100%",
    borderRadius: 999,
  },
  emptyState: {
    gap: 8,
    paddingVertical: 24,
    alignItems: "center",
  },
  emptyTitle: {
    color: palette.ink,
    fontSize: 18,
    fontWeight: "900",
  },
  emptyCopy: {
    color: palette.slate,
    textAlign: "center",
    lineHeight: 22,
  },
  nav: {
    position: "absolute",
    right: 0,
    bottom: 0,
    left: 0,
    flexDirection: "row",
    minHeight: 72 + bottomInset,
    paddingBottom: bottomInset,
    borderTopWidth: 1,
    borderTopColor: "rgba(216, 164, 59, 0.35)",
    backgroundColor: palette.emerald900,
  },
  navButton: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  navText: {
    color: palette.goldSoft,
    fontSize: 14,
    fontWeight: "900",
    textAlign: "center",
  },
  navTextActive: {
    color: palette.white,
  },
});
