import { Platform, StatusBar, StyleSheet } from "react-native";

const topInset = Platform.OS === "android" ? StatusBar.currentHeight || 0 : 0;
const bottomInset = Platform.OS === "android" ? 18 : 10;

export const styles = StyleSheet.create({
  app: {
    flex: 1,
    backgroundColor: "#eef3f6",
  },
  loadingScreen: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#eef3f6",
  },
  authScreen: {
    flex: 1,
    justifyContent: "center",
    paddingHorizontal: 20,
    paddingTop: 24 + topInset,
    paddingBottom: 24 + bottomInset,
    backgroundColor: "#eef3f6",
  },
  authPanel: {
    gap: 14,
    width: "100%",
    maxWidth: 430,
    alignSelf: "center",
  },
  brandMark: {
    width: 58,
    height: 58,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 18,
    backgroundColor: "#116b5f",
  },
  brandText: {
    color: "#ffffff",
    fontSize: 20,
    fontWeight: "900",
  },
  authTitle: {
    color: "#0d1824",
    fontSize: 32,
    fontWeight: "900",
  },
  authTitleRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 12,
  },
  authTitleText: {
    flex: 1,
    gap: 6,
  },
  authCopy: {
    color: "#5d6d7e",
    fontSize: 16,
    lineHeight: 24,
  },
  phoneShell: {
    flex: 1,
    alignSelf: "center",
    width: "100%",
    maxWidth: 430,
    backgroundColor: "#f8fafb",
  },
  header: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 12,
    paddingHorizontal: 16,
    paddingTop: 18 + topInset,
    paddingBottom: 14,
  },
  headerText: {
    flex: 1,
    minWidth: 0,
  },
  userEmail: {
    marginBottom: 4,
    color: "#677484",
    fontSize: 13,
  },
  title: {
    color: "#0d1824",
    fontSize: 27,
    fontWeight: "900",
  },
  headerActions: {
    alignItems: "flex-end",
    gap: 8,
  },
  languageSwitch: {
    flexDirection: "row",
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "#d7e0e6",
    borderRadius: 10,
    backgroundColor: "#ffffff",
  },
  languageButton: {
    minWidth: 34,
    height: 34,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 6,
  },
  languageButtonActive: {
    backgroundColor: "#137868",
  },
  languageText: {
    color: "#677484",
    fontSize: 12,
    fontWeight: "900",
  },
  languageTextActive: {
    color: "#ffffff",
  },
  logoutButton: {
    minWidth: 54,
    minHeight: 40,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 10,
    borderWidth: 1,
    borderColor: "#d7e0e6",
    borderRadius: 10,
    backgroundColor: "#ffffff",
  },
  logoutText: {
    color: "#5f6d7d",
    fontSize: 14,
    fontWeight: "900",
  },
  content: {
    gap: 14,
    paddingHorizontal: 16,
    paddingBottom: 96 + bottomInset,
  },
  card: {
    gap: 14,
    padding: 16,
    borderWidth: 1,
    borderColor: "#d7e0e6",
    borderRadius: 12,
    backgroundColor: "#ffffff",
  },
  statsCard: {
    flexDirection: "row",
    justifyContent: "space-between",
  },
  inlineStats: {
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 10,
  },
  stat: {
    flex: 1,
    gap: 5,
    minWidth: 0,
  },
  statLabel: {
    color: "#677484",
    fontSize: 12,
    minHeight: 30,
  },
  statValue: {
    color: "#0d1824",
    fontSize: 19,
    fontWeight: "900",
  },
  sectionTitle: {
    color: "#0d1824",
    fontSize: 20,
    fontWeight: "900",
  },
  helperText: {
    color: "#5d6d7e",
    fontSize: 16,
    lineHeight: 24,
  },
  field: {
    gap: 8,
  },
  label: {
    color: "#5d6d7e",
    fontSize: 13,
    fontWeight: "700",
  },
  input: {
    minHeight: 52,
    paddingHorizontal: 14,
    borderWidth: 1,
    borderColor: "#d7e0e6",
    borderRadius: 10,
    backgroundColor: "#ffffff",
    color: "#0d1824",
    fontSize: 16,
  },
  primaryButton: {
    minHeight: 58,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 12,
    backgroundColor: "#137868",
  },
  primaryPressed: {
    backgroundColor: "#0d554c",
  },
  primaryText: {
    color: "#ffffff",
    fontSize: 17,
    fontWeight: "900",
    textAlign: "center",
  },
  disabled: {
    opacity: 0.65,
  },
  linkButton: {
    alignSelf: "center",
    paddingVertical: 8,
  },
  linkText: {
    color: "#116b5f",
    fontSize: 15,
    fontWeight: "800",
  },
  errorText: {
    color: "#b42318",
  },
  statusText: {
    color: "#5d6d7e",
    fontSize: 15,
  },
  scanGrid: {
    gap: 10,
  },
  actionTile: {
    gap: 4,
    padding: 14,
    borderWidth: 1,
    borderColor: "#d7e0e6",
    borderRadius: 12,
    backgroundColor: "#f4f8f8",
  },
  pressed: {
    opacity: 0.75,
  },
  actionTitle: {
    color: "#0d1824",
    fontSize: 17,
    fontWeight: "900",
  },
  actionCopy: {
    color: "#677484",
    fontSize: 14,
  },
  selectedFile: {
    gap: 4,
    padding: 14,
    borderWidth: 1,
    borderColor: "#d7e0e6",
    borderRadius: 12,
    backgroundColor: "#ffffff",
  },
  selectedLabel: {
    color: "#677484",
    fontSize: 12,
  },
  selectedName: {
    color: "#0d1824",
    fontSize: 16,
    fontWeight: "800",
  },
  segmented: {
    flexDirection: "row",
    minHeight: 44,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "#d7e0e6",
    borderRadius: 10,
    backgroundColor: "#f4f8f8",
  },
  segmentButton: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 10,
  },
  segmentButtonActive: {
    backgroundColor: "#137868",
  },
  segmentText: {
    color: "#677484",
    fontSize: 14,
    fontWeight: "900",
  },
  segmentTextActive: {
    color: "#ffffff",
  },
  manualForm: {
    gap: 14,
  },
  chipGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  categoryChip: {
    minHeight: 38,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 12,
    borderWidth: 1,
    borderColor: "#d7e0e6",
    borderRadius: 999,
    backgroundColor: "#ffffff",
  },
  categoryChipActive: {
    borderColor: "#137868",
    backgroundColor: "#e6f4f1",
  },
  categoryChipText: {
    color: "#5d6d7e",
    fontSize: 13,
    fontWeight: "900",
  },
  categoryChipTextActive: {
    color: "#116b5f",
  },
  manualItem: {
    gap: 10,
    padding: 12,
    borderWidth: 1,
    borderColor: "#d7e0e6",
    borderRadius: 10,
    backgroundColor: "#f8fafb",
  },
  manualItemHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  twoColumn: {
    flexDirection: "row",
    gap: 10,
  },
  flexInput: {
    flex: 1,
    minWidth: 0,
  },
  secondaryButton: {
    minHeight: 48,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "#137868",
    borderRadius: 10,
    backgroundColor: "#ffffff",
  },
  secondaryText: {
    color: "#116b5f",
    fontSize: 15,
    fontWeight: "900",
  },
  smallButton: {
    minHeight: 34,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 10,
    borderRadius: 8,
    backgroundColor: "#edf1f4",
  },
  smallButtonText: {
    color: "#5d6d7e",
    fontSize: 12,
    fontWeight: "900",
  },
  actionRow: {
    gap: 6,
  },
  proCard: {
    borderColor: "#d7e0e6",
    backgroundColor: "#ffffff",
  },
  proCardActive: {
    borderColor: "#24a47a",
    backgroundColor: "#f1fbf6",
  },
  proHeader: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 10,
  },
  proBadge: {
    maxWidth: 118,
    paddingHorizontal: 8,
    paddingVertical: 7,
    overflow: "hidden",
    borderRadius: 8,
    backgroundColor: "#e6f4f1",
    color: "#116b5f",
    fontSize: 12,
    fontWeight: "900",
    textAlign: "center",
  },
  invoiceCard: {
    borderTopWidth: 1,
    borderTopColor: "#d7e0e6",
  },
  invoiceSummary: {
    minHeight: 70,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    paddingVertical: 12,
  },
  invoiceText: {
    flex: 1,
    gap: 4,
  },
  invoiceTitle: {
    color: "#0d1824",
    fontSize: 18,
    fontWeight: "900",
  },
  invoiceMeta: {
    color: "#677484",
    fontSize: 13,
  },
  invoiceAmount: {
    color: "#0d1824",
    fontSize: 17,
    fontWeight: "900",
    maxWidth: 120,
    textAlign: "right",
  },
  itemList: {
    gap: 10,
    paddingBottom: 14,
    paddingLeft: 12,
  },
  retryPanel: {
    gap: 10,
    paddingBottom: 14,
  },
  itemRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    paddingTop: 10,
    borderTopWidth: 1,
    borderTopColor: "#edf1f4",
  },
  itemName: {
    color: "#0d1824",
    fontSize: 15,
    fontWeight: "800",
  },
  itemPrice: {
    color: "#0d1824",
    fontSize: 15,
    fontWeight: "900",
  },
  categoryRow: {
    gap: 10,
    paddingVertical: 14,
    borderTopWidth: 1,
    borderTopColor: "#d7e0e6",
  },
  categoryRowSelected: {
    paddingHorizontal: 10,
    borderRadius: 10,
    backgroundColor: "#f1fbf6",
  },
  categoryMeta: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  categoryDot: {
    width: 12,
    height: 12,
    borderRadius: 6,
  },
  categoryName: {
    flex: 1,
    minWidth: 0,
    color: "#0d1824",
    fontSize: 17,
    fontWeight: "900",
  },
  categoryCount: {
    color: "#677484",
    fontSize: 13,
  },
  categoryAmount: {
    color: "#0d1824",
    fontSize: 16,
    fontWeight: "900",
    maxWidth: 110,
    textAlign: "right",
  },
  categoryBar: {
    height: 8,
    overflow: "hidden",
    borderRadius: 999,
    backgroundColor: "#edf1f4",
  },
  categoryFill: {
    height: "100%",
    borderRadius: 999,
  },
  emptyState: {
    gap: 8,
    paddingVertical: 24,
    alignItems: "center",
  },
  emptyTitle: {
    color: "#0d1824",
    fontSize: 18,
    fontWeight: "900",
  },
  emptyCopy: {
    color: "#677484",
    textAlign: "center",
    lineHeight: 22,
  },
  nav: {
    position: "absolute",
    right: 0,
    bottom: 0,
    left: 0,
    flexDirection: "row",
    minHeight: 72 + bottomInset,
    paddingBottom: bottomInset,
    borderTopWidth: 1,
    borderTopColor: "#d7e0e6",
    backgroundColor: "#ffffff",
  },
  navButton: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  navText: {
    color: "#677484",
    fontSize: 14,
    fontWeight: "900",
    textAlign: "center",
  },
  navTextActive: {
    color: "#116b5f",
  },
});
